_wandb:
    value:
        cli_version: 0.25.0
        e:
            li7o1a3tfujky7kvgtc1at4k8xd5tyax:
                codePath: 3DCLIP/train_clip3d_ecg.py
                codePathLocal: 3DCLIP/train_clip3d_ecg.py
                email: andreasaspe@gmail.com
                executable: /home/awias/miniconda3/envs/standard/bin/python
                git:
                    commit: e107803ace09954f2b9111162277ae02f1f26e31
                    remote: git@github.com:andreasaspe/NLDL2026_WinterSchool.git
                host: DTU-GPU-9
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/awias/Documents/code/NLDL2026_WinterSchool/3DCLIP/train_clip3d_ecg.py
                python: CPython 3.14.2
                root: /home/awias/Documents/code/NLDL2026_WinterSchool
                startedAt: "2026-02-25T09:33:41.837270Z"
                writerId: li7o1a3tfujky7kvgtc1at4k8xd5tyax
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.14.2
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 32
context_length:
    value: 36
embed_dim:
    value: 128
epochs:
    value: 1000
image_resolution:
    value: 192
label_smoothing:
    value: 0.1
learning_rate:
    value: 2.5e-05
transformer_heads:
    value: 4
transformer_layers:
    value: 4
transformer_width:
    value: 256
vision_layers:
    value:
        - 3
        - 4
        - 6
        - 3
vision_width:
    value: 64
warmup_epochs:
    value: 10
weight_decay:
    value: 0.001
