_wandb:
    value:
        cli_version: 0.25.0
        e:
            k1op1xcvybom2s4vc41033ql5is8yni2:
                codePath: 3DCLIP/train_clip3d_ecg.py
                codePathLocal: 3DCLIP/train_clip3d_ecg.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "3935709487104"
                        used: "244752814080"
                email: andreasaspe@gmail.com
                executable: /home/awias/miniconda3/envs/standard/bin/python
                git:
                    commit: c4b313a0f49594fcdac7ffe26acde655792697fc
                    remote: git@github.com:andreasaspe/NLDL2026_WinterSchool.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                      uuid: GPU-b189fb03-e696-386a-4e37-e471fc76d8b7
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                      uuid: GPU-bb791e03-0b49-e91a-e278-28631a20909f
                host: DTU-GPU-9
                memory:
                    total: "269560815616"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/awias/Documents/code/NLDL2026_WinterSchool/3DCLIP/train_clip3d_ecg.py
                python: CPython 3.14.2
                root: /home/awias/Documents/code/NLDL2026_WinterSchool
                startedAt: "2026-02-25T09:35:07.853926Z"
                writerId: k1op1xcvybom2s4vc41033ql5is8yni2
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.14.2
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 32
context_length:
    value: 36
embed_dim:
    value: 128
epochs:
    value: 1000
image_resolution:
    value: 192
label_smoothing:
    value: 0.1
learning_rate:
    value: 2.5e-05
transformer_heads:
    value: 4
transformer_layers:
    value: 4
transformer_width:
    value: 256
vision_layers:
    value:
        - 3
        - 4
        - 6
        - 3
vision_width:
    value: 64
warmup_epochs:
    value: 10
weight_decay:
    value: 0.001
